name: Create changelog
inputs:
  from-tag:
    required: true
    type: string
  to-tag:
    required: true
    type: string
outputs:
  changelog:
    description: "Changelog output body"
    value: ${{ steps.changelog.outputs.content }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: orhun/git-cliff-action@v2
      id: changelog
      with:
        config: fixtures/cliff.toml
        args: -v ${{ inputs.from-tag }}..${{ inputs.to-tag }}
