name: Auto Promote Argo Workflow
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      config-repo:
        required: true
        type: string
      config-file:
        required: true
        type: string
      config-key:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: main
      docker-image-tag:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: checkout-config-repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          repository: ${{ inputs.config-repo }}
          ssh-key: ${{ secrets.SSH_KEY }}
          sparse-checkout: ${{ inputs.config-file }}
          sparse-checkout-cone-mode: false
      - name: update-workflow
        run: |
          yq -i '.${{ inputs.config-key }}.tag = "${{ inputs.docker-image-tag }}"' ${{ inputs.config-file }}
          git config user.name github-service-known
          git config user.email github.service@known.is
          git add ${{ inputs.config-file }}
          git commit -m "deploy ${{ inputs.config-key }} to ${{ inputs.docker-image-tag }}"
      - name: Push to ${{ inputs.branch }}
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 3
          retry_on: error
          command: git pull --rebase origin ${{ inputs.branch }} && git push origin ${{ inputs.branch }}
