name: Reusable Check Runner Type

# This workflow job will determine whether we are running on a
# self-hosted runner.

on:
  workflow_call:
    outputs:
      runner:
        description: "Runner Type"
        value: ${{ jobs.check-runner-type.outputs.runner-type }}

    secrets:
      SELF_HOSTED_RUNNER:
        required: false
        description: "Flag to signal we're on a self hosted runner."

jobs:
  check-runner-type:
    runs-on: ubuntu-latest
    outputs:
      runner-type: ${{ steps.runner-type.outputs.runner-type }}
    steps:
      - id: runner-type
        run: |
          if [ -z ${{ secrets.SELF_HOSTED_RUNNER }} ]; then
            echo "runner-type=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner-type=self-hosted" >> $GITHUB_OUTPUT
          fi
