name: Reusable Docker Push Workflow
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: >
          The sub-directory to run commands out of
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: >
          The name of the environment to run on. This defaults to
          'ubuntu-latest'
      build:
        required: false
        type: boolean
        default: true
        description: Whether to run "make build"
      push:
        required: false
        type: boolean
        default: true
        description: Whether to run "make push"
    outputs:
      image-tag:
        description: "The image tag"
        value: ${{ jobs.build-and-push.outputs.image-tag }}
    secrets:
      ECR_AWS_ACCESS_KEY_ID:
        required: true
      ECR_AWS_SECRET_ACCESS_KEY:
        required: true
      POETRY_HTTP_BASIC_SCHIRESON_USERNAME:
        required: false
      POETRY_HTTP_BASIC_SCHIRESON_PASSWORD:
        required: false
jobs:
  build-and-push:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    outputs:
      image-tag: ${{ steps.get-image-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Get image tag
        id: get-image-tag
        run: |
          IMAGE_TAG=$(git rev-parse --short=8 HEAD)
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Build Docker Images
        if: ${{ inputs.build }}
        env:
          POETRY_HTTP_BASIC_SCHIRESON_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_SCHIRESON_USERNAME }}
          POETRY_HTTP_BASIC_SCHIRESON_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_SCHIRESON_PASSWORD }}
        run: |
          make build
      - name: Configure ECR AWS Credentials
        if: ${{ inputs.runs-on != 'self-hosted' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Push Docker Images
        if: ${{ inputs.push }}
        run: |
          make docker-login-server
          make push
