name: Publish Artifactory Package
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: >
          The sub-directory to run commands out of
      python-version:
        required: false
        type: string
        default: "3.10"
        description: >
          The python version to utilize in workflow.
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
        description: >
          The name of the environment to run on. This defaults to
          'ubuntu-latest'
    secrets:
      POETRY_HTTP_BASIC_SCHIRESON_USERNAME:
        required: true
      POETRY_HTTP_BASIC_SCHIRESON_PASSWORD:
        required: true
      POETRY_REPOSITORIES_PUBLISH_URL:
        required: false
      POETRY_HTTP_BASIC_KNOWN_USERNAME:
        required: false
      POETRY_HTTP_BASIC_KNOWN_PASSWORD:
        required: false
jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared --enable-optimizations
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: ${{ inputs.working-directory }}/.venv
          key: venv-${{ runner.os }}-${{ inputs.runs-on }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Publish Client
        env:
          POETRY_REPOSITORIES_PUBLISH_URL: ${{ secrets.POETRY_REPOSITORIES_PUBLISH_URL }}
          POETRY_HTTP_BASIC_SCHIRESON_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_SCHIRESON_USERNAME }}
          POETRY_HTTP_BASIC_SCHIRESON_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_SCHIRESON_PASSWORD }}
          POETRY_HTTP_BASIC_KNOWN_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_KNOWN_USERNAME }}
          POETRY_HTTP_BASIC_KNOWN_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_KNOWN_PASSWORD }}
        run: make publish
